/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package clinica.views;

import clinica.dao.UsuarioDAO;
import clinica.enums.ETipoUsuario;
import clinica.model.Usuario;
import javax.swing.JOptionPane;


/**
 *
 * @author steph
 */
public class TelaLogin extends javax.swing.JFrame {

    /**
     * Creates new form TelaLogin
     */
    public TelaLogin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JLTitulo = new javax.swing.JLabel();
        JLLogin = new javax.swing.JLabel();
        JTLogin = new javax.swing.JTextField();
        JLSenha = new javax.swing.JLabel();
        JTSenha = new javax.swing.JPasswordField();
        JCTipoUsuario = new javax.swing.JComboBox<>();
        JLTipoUsuario = new javax.swing.JLabel();
        JBLogar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        JLTitulo.setFont(new java.awt.Font("Lucida Handwriting", 1, 14)); // NOI18N
        JLTitulo.setText("Clinica Du Gustin");

        JLLogin.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        JLLogin.setText("Login:");

        JTLogin.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        JLSenha.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        JLSenha.setText("Senha:");

        JTSenha.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        JCTipoUsuario.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        JCTipoUsuario.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        JCTipoUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JCTipoUsuarioActionPerformed(evt);
            }
        });

        JLTipoUsuario.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        JLTipoUsuario.setText("Tipo de Usuário: ");

        JBLogar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        JBLogar.setText("Logar");
        JBLogar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBLogarActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sair16px.png"))); // NOI18N
        jButton1.setText("Sair");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/login128px.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(127, 127, 127)
                        .addComponent(JBLogar))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(34, 34, 34)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(JLLogin)
                                    .addComponent(JLSenha)
                                    .addComponent(JLTipoUsuario)
                                    .addComponent(JTLogin)
                                    .addComponent(JTSenha)
                                    .addComponent(JCTipoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addComponent(JLTitulo)))
                .addContainerGap(42, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JLTitulo)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(JLLogin)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JTLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(JLSenha)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JTSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(JLTipoUsuario))
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JCTipoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(JBLogar)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JBLogarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBLogarActionPerformed
        try{
            if(!"".equals(JTLogin.getText()) && !"".equals(JTSenha.getText()))
            {
                String login = JTLogin.getText();
                String senha = JTSenha.getText(); 
                String tipoUsuario = (String) JCTipoUsuario.getSelectedItem();                
                ETipoUsuario etipoUsuario = ETipoUsuario.valueOf(tipoUsuario);

                UsuarioDAO usuarioDAO = new UsuarioDAO();                
                Usuario usuario = usuarioDAO.logar(login, senha, tipoUsuario);
                
                if(usuario != null && tipoUsuario.equals("CADASTRO")){
                    TelaColeta tela = new TelaColeta();
                    tela.setVisible(true);
                    this.setVisible(false);
                }
                else if(usuario != null && tipoUsuario.equals("RESPONSAVELTECNICO")){
                    TelaExame tela = new TelaExame();
                    tela.setVisible(true);
                    this.setVisible(false);
                }
                else if(usuario != null && tipoUsuario.equals("SUPERVISOR")){
                    TelaRelatorio tela = new TelaRelatorio();
                    tela.setVisible(true);
                    this.setVisible(false);
                }
                else if(usuario != null && tipoUsuario.equals("PACIENTE")){
                    TelaPaciente tela = new TelaPaciente();
                    tela.prepareUsuario(usuario);
                    tela.setVisible(true);
                    this.setVisible(false);
                }
                else if(usuario != null && tipoUsuario.equals("ADMINISTRADOR")){
                    TelaAdministrador tela = new TelaAdministrador();
                    tela.setVisible(true);
                    this.setVisible(false);
                }
                else {
                    JOptionPane.showMessageDialog(null, "Login e/ou senha incorretos.");
                } 
            }
            else {
                JOptionPane.showMessageDialog(null, "Campos login e senha sao obrigatórios.");
            }  
        }
        catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
    }//GEN-LAST:event_JBLogarActionPerformed

    private void JCTipoUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JCTipoUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JCTipoUsuarioActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        preencheCombo();
    }//GEN-LAST:event_formWindowOpened

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed
    
    String[] dados = {"CADASTRO", "RESPONSAVELTECNICO", "SUPERVISOR", "PACIENTE", "ADMINISTRADOR"};
    
    private void preencheCombo() {        
        
        JCTipoUsuario.removeAllItems(); 

        for(int i = 0; i < dados.length; i++) {
            JCTipoUsuario.addItem(dados[i]);
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBLogar;
    private javax.swing.JComboBox<String> JCTipoUsuario;
    private javax.swing.JLabel JLLogin;
    private javax.swing.JLabel JLSenha;
    private javax.swing.JLabel JLTipoUsuario;
    private javax.swing.JLabel JLTitulo;
    private javax.swing.JTextField JTLogin;
    private javax.swing.JPasswordField JTSenha;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
