/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package clinica.views;

import clinica.dao.ColetaDAO;
import clinica.dao.UsuarioDAO;
import clinica.enums.EMaterialColetado;
import clinica.model.Coleta;
import clinica.model.Usuario;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author steph
 */
public class TelaColeta extends javax.swing.JFrame {

    /**
     * Creates new form TelaCadastro
     */
    public TelaColeta() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        JBMColetado = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        JRSim = new javax.swing.JRadioButton();
        JRNao = new javax.swing.JRadioButton();
        JBSalvar = new javax.swing.JButton();
        JBSair = new javax.swing.JButton();
        JBVoltar = new javax.swing.JButton();
        JCPaciente = new javax.swing.JComboBox<>();
        JCColetor = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        JRAte60 = new javax.swing.JRadioButton();
        JRMais60 = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Lucida Handwriting", 1, 18)); // NOI18N
        jLabel1.setText("Clinica Du Gustin");

        jLabel2.setFont(new java.awt.Font("Lucida Handwriting", 1, 14)); // NOI18N
        jLabel2.setText("Coleta");

        jLabel3.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel3.setText("Coletor:");

        jLabel4.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel4.setText("Paciente:");

        jLabel5.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel5.setText("Material Coletado:");

        JBMColetado.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        JBMColetado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel6.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel6.setText("Comorbidade:");

        buttonGroup1.add(JRSim);
        JRSim.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        JRSim.setSelected(true);
        JRSim.setText("Sim");

        buttonGroup1.add(JRNao);
        JRNao.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        JRNao.setText("Nao");

        JBSalvar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        JBSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/salvar20px.png"))); // NOI18N
        JBSalvar.setText("Salvar");
        JBSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBSalvarActionPerformed(evt);
            }
        });

        JBSair.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        JBSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sair16px.png"))); // NOI18N
        JBSair.setText("Sair");
        JBSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBSairActionPerformed(evt);
            }
        });

        JBVoltar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        JBVoltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/voltar20px.png"))); // NOI18N
        JBVoltar.setText("Voltar");
        JBVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBVoltarActionPerformed(evt);
            }
        });

        JCPaciente.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        JCPaciente.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        JCColetor.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        JCColetor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel7.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel7.setText("Idade:");

        buttonGroup2.add(JRAte60);
        JRAte60.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        JRAte60.setSelected(true);
        JRAte60.setText("Até 60 anos");

        buttonGroup2.add(JRMais60);
        JRMais60.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        JRMais60.setText("Mais de 60 anos");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel3)
                    .addComponent(jLabel6)
                    .addComponent(JBVoltar))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(JRAte60)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(JRMais60))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(JCColetor, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(JCPaciente, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(JBSalvar)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(JRSim)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(JRNao)))
                                .addComponent(JBMColetado, javax.swing.GroupLayout.Alignment.LEADING, 0, 250, Short.MAX_VALUE)))
                        .addGap(0, 11, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(JBSair)
                        .addGap(56, 56, 56))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(97, 97, 97)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(154, 154, 154)
                        .addComponent(jLabel2)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(JCColetor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(JCPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(JRAte60)
                    .addComponent(JRMais60))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(JBMColetado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(JRSim)
                    .addComponent(JRNao))
                .addGap(18, 18, 18)
                .addComponent(JBSalvar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JBSair)
                    .addComponent(JBVoltar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JBVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBVoltarActionPerformed
        TelaLogin tela = new TelaLogin();
        tela.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_JBVoltarActionPerformed

    private void JBSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBSairActionPerformed
        System.exit(0);
    }//GEN-LAST:event_JBSairActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        try {
            preencheCombo();
        } catch (SQLException ex) {
            Logger.getLogger(TelaColeta.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(TelaColeta.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_formWindowOpened

    private void JBSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBSalvarActionPerformed
        try{
                int idx = JCColetor.getSelectedIndex();                
                Usuario coletor = coletores.get(idx);
                
                int idx2 = JCPaciente.getSelectedIndex();                
                Usuario paciente = pacientes.get(idx2);
                
                Boolean idade = false;
                if(JRAte60.isSelected()){
                    idade = true;
                }
                else if(JRMais60.isSelected()){
                    idade = false;
                }
                
                String materialColetado = (String) JBMColetado.getSelectedItem();                
                EMaterialColetado eMaterialColetado = EMaterialColetado.valueOf(materialColetado);
                
                Boolean comorbidade = false;
                if(JRSim.isSelected()){
                    comorbidade = true;
                }
                else if(JRNao.isSelected()){
                    comorbidade = false;
                }
  
                Coleta coleta;
                
                ColetaDAO coletaDAO = new ColetaDAO();
                
                if(operacao == null){
                    coleta = new Coleta(0, coletor, paciente, idade, eMaterialColetado, comorbidade);
                    coletaDAO.salvar(coleta);
                }
                else if(operacao.equals("Editar")){
                    coleta = new Coleta(coletaGlobal.getId(), coletor, paciente, idade, eMaterialColetado, comorbidade);
                    coletaDAO.alterar(coleta);
                }
                
                JOptionPane.showMessageDialog(null, "Operação realizada com Sucesso!!!");
                TelaLogin tela = new TelaLogin();
                tela.setVisible(true);
                this.setVisible(false);             
        }
        catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
    }//GEN-LAST:event_JBSalvarActionPerformed
    
    String[] dados = {"ASPIRADOTRAQUEAL", "ESCARRO", "LAVADOBRONCOALVEOLAR", "ASPIRADOBRONQUICO", 
    "ASPIRADONASOFARINGEO", "SWABCOMBINADODEOROFARINGEENASOFARINGE",
    "SECRECAOTRAQUEAL", "SWABDENASOFARINGE"};
    
    ArrayList<Usuario> pacientes;
    ArrayList<Usuario> coletores;
    
    private void preencheCombo() throws SQLException, ClassNotFoundException {        
        
        JBMColetado.removeAllItems(); 

        for(int i = 0; i < dados.length; i++) {
            JBMColetado.addItem(dados[i]);
        }
        
        pacientes = new UsuarioDAO().buscarPacientes();
        JCPaciente.removeAllItems();
        
        for(int i = 0; i < pacientes.size(); i++){
            JCPaciente.addItem(pacientes.get(i).getNome());
        }
        
        coletores = new UsuarioDAO().buscarCadastros();
        JCColetor.removeAllItems();
        
        for(int i = 0; i < coletores.size(); i++){
            JCColetor.addItem(coletores.get(i).getNome());
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaColeta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaColeta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaColeta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaColeta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaColeta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> JBMColetado;
    private javax.swing.JButton JBSair;
    private javax.swing.JButton JBSalvar;
    private javax.swing.JButton JBVoltar;
    private javax.swing.JComboBox<String> JCColetor;
    private javax.swing.JComboBox<String> JCPaciente;
    private javax.swing.JRadioButton JRAte60;
    private javax.swing.JRadioButton JRMais60;
    private javax.swing.JRadioButton JRNao;
    private javax.swing.JRadioButton JRSim;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    // End of variables declaration//GEN-END:variables

    private Coleta coletaGlobal;
    private String operacao;
    
    void preparedEdit(Coleta col, String op) {
        this.coletaGlobal = col;
        this.operacao = op;

        JCPaciente.setSelectedItem(coletaGlobal.getColetor());
        JCPaciente.setSelectedItem(coletaGlobal.getPaciente());
        JRAte60.setSelected(coletaGlobal.getIdade());
        JRMais60.setSelected(!coletaGlobal.getIdade());
        JBMColetado.setSelectedItem(coletaGlobal.getMaterialColetado());
        JRSim.setSelected(coletaGlobal.getComorbidade());
        JRNao.setSelected(!coletaGlobal.getComorbidade());
    }
}
