/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package clinica.views;

import clinica.dao.ExameDAO;
import clinica.model.Exame;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author steph
 */
public class TelaRelatorio extends javax.swing.JFrame {

    /**
     * Creates new form TelaSupervisor
     */
    public TelaRelatorio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        JLRelatorioDiario = new javax.swing.JLabel();
        JLPacientesAtendidos = new javax.swing.JLabel();
        JLTestesUtilizados = new javax.swing.JLabel();
        JLExamesDetectado = new javax.swing.JLabel();
        JLExamesNaoDetectado = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        JLPForaDoPrazo = new javax.swing.JLabel();
        JLPPoucoMaterialColetado = new javax.swing.JLabel();
        JLPExamesInconclusivos = new javax.swing.JLabel();
        JLExamesInvalidos = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        JBEnviar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Lucida Handwriting", 1, 18)); // NOI18N
        jLabel1.setText("Clinica du Gustin");

        JLRelatorioDiario.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        JLRelatorioDiario.setText("Relatório Diário: ");

        JLPacientesAtendidos.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        JLPacientesAtendidos.setText("   Número de Pacientes Atendidos");

        JLTestesUtilizados.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        JLTestesUtilizados.setText("   Testes utilizados");

        JLExamesDetectado.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        JLExamesDetectado.setText("   Exames Detectado");

        JLExamesNaoDetectado.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        JLExamesNaoDetectado.setText("   Exames Nao Detectado");

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/qrcode.png"))); // NOI18N

        JLPForaDoPrazo.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        JLPForaDoPrazo.setText("   Paciente para recoleta, motivo: amostra fora do prazo (24h)");

        JLPPoucoMaterialColetado.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        JLPPoucoMaterialColetado.setText("   Paciente para recoleta, motivo: Pouco Material Coletado");

        JLPExamesInconclusivos.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        JLPExamesInconclusivos.setText("   Paciente com exames inconclusivos e os testes foram refeitos");

        JLExamesInvalidos.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        JLExamesInvalidos.setText("   Exame Inválido");

        jLabel10.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        jLabel10.setText("Assinatura Responsável Técnico");

        jLabel11.setText("_______________________________________");

        JBEnviar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/enviar20px.png"))); // NOI18N
        JBEnviar.setText("Enviar");
        JBEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBEnviarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(JLPacientesAtendidos, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(JLExamesDetectado, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 157, Short.MAX_VALUE)
                                .addComponent(JLTestesUtilizados, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(JLExamesNaoDetectado)
                            .addComponent(JLPForaDoPrazo)
                            .addComponent(JLPPoucoMaterialColetado)
                            .addComponent(JLExamesInvalidos)
                            .addComponent(JLPExamesInconclusivos))
                        .addContainerGap(15, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(76, 76, 76)
                                .addComponent(jLabel10)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(JBEnviar)
                                    .addComponent(jLabel11))
                                .addGap(23, 23, 23))))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(JLRelatorioDiario, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(68, 68, 68))
            .addGroup(layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(31, 31, 31)
                .addComponent(JLRelatorioDiario, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addComponent(JLPacientesAtendidos, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JLTestesUtilizados, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JLExamesDetectado, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JLExamesNaoDetectado, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JLPForaDoPrazo, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JLPPoucoMaterialColetado, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JLPExamesInconclusivos, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JLExamesInvalidos, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel10)))
                .addGap(30, 30, 30)
                .addComponent(JBEnviar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        try {
            ArrayList<Exame> exames = new ArrayList();
            exames = new ExameDAO().buscarDataAtual();   
            
            SimpleDateFormat formatter = new SimpleDateFormat("dd/MM/yyyy");
            
            int contInvalido = 0;
            int contInconclusivo = 0;
            int contNaoDetectado = 0;
            int contDetectado = 0;
            int contPacientesAtendidos = new ExameDAO().buscarQuantidadePacientesDataAtual();
            int contRecoletaForaPrazo = 0;
            int contPoucoMaterial = 0;
            
            for(Exame e : exames){
                if(e.getResultado().toString().equals("INVALIDO")){
                    contInvalido++;
                }
                
                if(e.getResultado().toString().equals("INCONCLUSIVO")){
                    contInconclusivo++;
                }
                
                if(e.getResultado().toString().equals("NAODETECTADO")){
                    contNaoDetectado++;
                }
                
                if(e.getResultado().toString().equals("DETECTADO")){
                    contDetectado++;
                }
                
                if(e.getResultado().toString().equals("RECOLETAFORAPRAZO")){
                    contRecoletaForaPrazo++;
                }
                
                if(e.getResultado().toString().equals("RECOLETAPOUCOMATERIAL")){
                    contPoucoMaterial++;
                }
            }
            
            JLRelatorioDiario.setText(JLRelatorioDiario.getText() + formatter.format(new Date()));
            JLPacientesAtendidos.setText( contPacientesAtendidos + JLPacientesAtendidos.getText());
            JLTestesUtilizados.setText( exames.size() + JLTestesUtilizados.getText());
            JLExamesDetectado.setText( contDetectado + JLExamesDetectado.getText());
            JLExamesNaoDetectado.setText( contNaoDetectado + JLExamesNaoDetectado.getText());
            JLPForaDoPrazo.setText( contRecoletaForaPrazo + JLPForaDoPrazo.getText());
            JLPPoucoMaterialColetado.setText( contPoucoMaterial + JLPPoucoMaterialColetado.getText());
            JLPExamesInconclusivos.setText( contInconclusivo + JLPExamesInconclusivos.getText());
            JLExamesInvalidos.setText( contInvalido + JLExamesInvalidos.getText());
            
            
            
        } catch (SQLException ex) {
            Logger.getLogger(TelaRelatorio.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(TelaRelatorio.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_formWindowOpened

    private void JBEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBEnviarActionPerformed
        JOptionPane.showMessageDialog(null, "Relatório enviado com sucesso!!");
        TelaLogin tela = new TelaLogin();
        tela.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_JBEnviarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaRelatorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaRelatorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaRelatorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaRelatorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaRelatorio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBEnviar;
    private javax.swing.JLabel JLExamesDetectado;
    private javax.swing.JLabel JLExamesInvalidos;
    private javax.swing.JLabel JLExamesNaoDetectado;
    private javax.swing.JLabel JLPExamesInconclusivos;
    private javax.swing.JLabel JLPForaDoPrazo;
    private javax.swing.JLabel JLPPoucoMaterialColetado;
    private javax.swing.JLabel JLPacientesAtendidos;
    private javax.swing.JLabel JLRelatorioDiario;
    private javax.swing.JLabel JLTestesUtilizados;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables
}
