/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package clinica.views;

import clinica.dao.ColetaDAO;
import clinica.dao.ExameDAO;
import clinica.dao.UsuarioDAO;
import clinica.enums.EResultado;
import clinica.model.Coleta;
import clinica.model.Exame;
import clinica.model.Usuario;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author steph
 */
public class TelaExame extends javax.swing.JFrame {

    /**
     * Creates new form TelaResponsavelTecnico
     */
    public TelaExame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        JBRTecnico = new javax.swing.JComboBox<>();
        JCColeta = new javax.swing.JComboBox<>();
        JLNumTeste = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        JCResultado = new javax.swing.JComboBox<>();
        JBSalvar = new javax.swing.JButton();
        JBSair = new javax.swing.JButton();
        JBVoltar = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        JLData = new javax.swing.JLabel();
        JFTNumTestes = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Lucida Handwriting", 1, 18)); // NOI18N
        jLabel1.setText("Clinica du Gustin");

        jLabel2.setFont(new java.awt.Font("Lucida Handwriting", 1, 14)); // NOI18N
        jLabel2.setText("Exame");

        jLabel3.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel3.setText("Responsável Tecnico:");

        jLabel4.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel4.setText("Coleta:");

        JBRTecnico.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        JBRTecnico.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        JCColeta.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        JCColeta.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        JLNumTeste.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        JLNumTeste.setText("Numero de testes:");

        jLabel6.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel6.setText("Resultado:");

        JCResultado.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        JCResultado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        JBSalvar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        JBSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/salvar20px.png"))); // NOI18N
        JBSalvar.setText("Salvar");
        JBSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBSalvarActionPerformed(evt);
            }
        });

        JBSair.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        JBSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sair16px.png"))); // NOI18N
        JBSair.setText("Sair");
        JBSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBSairActionPerformed(evt);
            }
        });

        JBVoltar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        JBVoltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/voltar20px.png"))); // NOI18N
        JBVoltar.setText("Voltar");
        JBVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBVoltarActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel7.setText("Data:");

        JFTNumTestes.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addGap(1, 1, 1))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(JBVoltar)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(jLabel3)
                                                .addComponent(jLabel7)
                                                .addComponent(jLabel4)
                                                .addComponent(jLabel6)
                                                .addComponent(JLNumTeste, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGap(18, 18, 18)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel2)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(JCColeta, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(JCResultado, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(JFTNumTestes, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(JBRTecnico, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                                .addGap(6, 6, 6)
                                .addComponent(JLData, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(JBSair)
                                .addGap(107, 107, 107))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(141, 141, 141)
                        .addComponent(JBSalvar)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(77, 77, 77)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4)
                                    .addComponent(JCColeta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(JLNumTeste)
                                    .addComponent(JFTNumTestes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel6)
                                    .addComponent(JCResultado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3)
                                    .addComponent(JBRTecnico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(15, 15, 15)
                                .addComponent(jLabel7))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(106, 106, 106)
                        .addComponent(JLData)))
                .addGap(36, 36, 36)
                .addComponent(JBSalvar)
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(JBSair)
                    .addComponent(JBVoltar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JBSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBSairActionPerformed
        System.exit(0);
    }//GEN-LAST:event_JBSairActionPerformed

    private void JBVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBVoltarActionPerformed
        TelaLogin tela = new TelaLogin();
        tela.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_JBVoltarActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        try {
            preencheCombo();
            
            SimpleDateFormat formatter = new SimpleDateFormat("dd/MM/yyyy");
            JLData.setText(formatter.format(new Date()).toString()); 
            
        } catch (SQLException ex) {
            Logger.getLogger(TelaExame.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(TelaExame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_formWindowOpened

    private void JBSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBSalvarActionPerformed
        try{
            if(!"".equals(JFTNumTestes.getText()))
            {
                int numeroTeste = Integer.parseInt(JFTNumTestes.getText());
                
                String resultado = (String) JCResultado.getSelectedItem();                
                EResultado eResultado = EResultado.valueOf(resultado);
                
                int idx = JBRTecnico.getSelectedIndex();                
                Usuario responsaTecnico = responsavelTecnicos.get(idx);
                
                int idx2 = JCColeta.getSelectedIndex();                
                Coleta coleta = coletas.get(idx2);
  
                Exame exame;
                
                ExameDAO exameDAO = new ExameDAO();
                
                if(operacao == null){
                    exame = new Exame(0, responsaTecnico, coleta.getPaciente(), coleta, numeroTeste, eResultado);
                    exameDAO.salvar(exame);
                }
                else if(operacao.equals("Editar")){
                    exame = new Exame(exameGlobal.getId(), responsaTecnico, coleta.getPaciente(), coleta, numeroTeste, eResultado);
                    exameDAO.alterar(exame);
                }
                
                JOptionPane.showMessageDialog(null, "Operação realizada com Sucesso!!!");
                TelaLogin tela = new TelaLogin();
                tela.setVisible(true);
                this.setVisible(false);
            }
            else {
                JOptionPane.showMessageDialog(null, "Campo numero de teste é obrigatório.");
            }  
        }
        catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
    }//GEN-LAST:event_JBSalvarActionPerformed

    String[] dados = {"INCONCLUSIVO", "INVALIDO", "DETECTADO", "RECOLETAFORAPRAZO", "RECOLETAPOUCOMATERIAL", 
    "NAODETECTADO"};
    
    ArrayList<Coleta> coletas;
    ArrayList<Usuario> responsavelTecnicos;
    
    private void preencheCombo() throws SQLException, ClassNotFoundException {        
        
        JCResultado.removeAllItems(); 

        for(int i = 0; i < dados.length; i++) {
            JCResultado.addItem(dados[i]);
        }
        
        coletas = new ColetaDAO().buscarTodos();
        JCColeta.removeAllItems();
        
        for(int i = 0; i < coletas.size(); i++){
            JCColeta.addItem(coletas.get(i).getId() + " - " + coletas.get(i).getPaciente().getNome());  
        }
        
        responsavelTecnicos = new UsuarioDAO().buscarResponsaveisTecnicos();
        JBRTecnico.removeAllItems();
        
        for(int i = 0; i < responsavelTecnicos.size(); i++){
            JBRTecnico.addItem(responsavelTecnicos.get(i).getNome());  
        }
    }

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaExame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaExame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaExame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaExame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaExame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> JBRTecnico;
    private javax.swing.JButton JBSair;
    private javax.swing.JButton JBSalvar;
    private javax.swing.JButton JBVoltar;
    private javax.swing.JComboBox<String> JCColeta;
    private javax.swing.JComboBox<String> JCResultado;
    private javax.swing.JTextField JFTNumTestes;
    private javax.swing.JLabel JLData;
    private javax.swing.JLabel JLNumTeste;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    // End of variables declaration//GEN-END:variables

    private Exame exameGlobal;
    private String operacao;
    
    void preparedEdit(Exame exa, String op) {
        this.exameGlobal = exa;
        this.operacao = op;

        JBRTecnico.setSelectedItem(exameGlobal.getResponsavelTecnico());
        JCColeta.setSelectedItem(exameGlobal.getColeta());
        JFTNumTestes.setText(exameGlobal.getNumeroTeste() + "");
        JCResultado.setSelectedItem(exameGlobal.getResultado());
    }
    
}
